[package]
name = "spotlight"
version = "0.0.0"

[dependencies]
mlua = { version = "0.9.8" , features = ["lua54", "async", "send"]}
dirs = "5.0.1"
anyhow = "1.0.86"
log = "0.4.21"

[features]
default = [ "gtk", "wayland", "xorg" ]
qt = []
tui = []
gtk = []
wayland = []
xorg = []
